# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- fork-publish

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Gradle@2
  env:
    BINTRAY_USER: $(BINTRAY_USER)
    BINTRAY_API_KEY: $(BINTRAY_API_KEY)
  inputs:
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: false
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'bintrayUpload'
