name: "✍️ Create a Task"
description: Create a new task.
labels: ["Type/Task"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear description of what needs to be done.
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: Enter product/component version.
    validations:
      required: false
